spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saltdb
    username: ${postgres.username}
    password: ${postgres.password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  config:
    import: optional:secret.yml

